config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),

    path('users/', include('users.urls')),
]

post/urls.py
from django.urls import path
from . import views
from . import services as sc


urlpatterns = [
    path('', views.home, name='home'),
    path('create/', sc.post_create, name='post_create'),

    path('<slug:slug>/', views.post_detail, name='post_detail'),
    path('<slug:slug>/update/', sc.post_udpate, name='post_update'),
    path('<slug:slug>/delete/', sc.post_delete, name='post_delete'),
]

users/urls.py
from django.urls import path
from . import views
from .services import user_register, user_login

app_name = 'users'

urlpatterns = [
    path('profile/', views.profile_view, name='profile'),
    path('register/', user_register, name='user_register'),
    path('login/', user_login, name='user_login'),
]

post/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField('Title', max_length=150)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    discription = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        return super().save(*args, **kwargs)


class Category(models.Model):
    title = models.CharField('Title', max_length=150)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment author: {self.author}'

users/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    """User model"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.user.username

post/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'category', 'discription')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)

post/views.py
from django.shortcuts import render

from .forms import CommentForm
from .models import Post
from .services import save_comment


def home(request):
    posts = Post.objects.all().select_related('author', 'category').\
        values('author__username', 'title', 'category__title', 'discription',
               'create_at', 'slug')
    return render(request, 'main/home.html', {'posts': posts})


def post_detail(request, slug):
    post = Post.objects.get(slug=slug)
    comments = post.comments.all()
    form = CommentForm()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        save_comment(request, form, post)  # checked that the form is valid and will save the form

    context = {
        'post': post,
        'comments': comments,
        'form': form
    }

    return render(request, 'main/post_detail.html', context=context)

users/views.py
from django.shortcuts import render

from post.models import Post
from users.models import Profile


def profile_view(request):
    profile = Profile.objects.get(user=request.user)
    user_posts = Post.objects.filter(author_id=profile.user.id)

    context = {
        'profile': profile,
        'user_posts': user_posts,
    }
    return render(request, 'main/profile.html', context)

post/templates/main/form/post_create.html
{% extends 'main/base.html' %}

{% block title %}Create{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            <p>{{ field }}</p>
            {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
    {% endfor %}
    <button type="submit">Create</button>
</form>
{% endblock %}

post/templates/main/form/post_delete.html
{% extends 'main/base.html' %}

{% block title %}Delete{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <h3>{{ post }}</h3>
    <br>
    <button type="submit">Delete</button>
</form>
{% endblock %}

post/templates/main/form/post_update.html
{% extends 'main/base.html' %}

{% block title %}Update{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            <p>{{ field }}</p>
            {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
    {% endfor %}
    <button type="submit">Update</button>
</form>
{% endblock %}

post/templates/main/home.html
{% extends 'main/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="list-group w-25 m-3">
{% for post in posts  %}
    <a href="{% url 'post_detail' post.slug %}"
       class="list-group-item list-group-item-action flex-column align-items-start">
        <span style="display: block;"><small style="font-size: 14px;">{{ post.category__title }}</small></span>

    <div class="d-flex w-1 justify-content-between align-items-center">
        <h5 style="margin: 0; padding: 0;" class="mb-1">{{ post.title }}
        </h5>

        <small style="width: 120px;">{{ post.create_at|date:"D d M Y" }}</small>
    </div>
        <p class="mb-1" style="font-size: 17px;">{{ post.discription|truncatewords:17 }}</p>
        <small>{{ post.author__username }}</small>
    </a>

{% endfor %}
</div>
{% endblock %}

post/templates/main/path/head.html
<div class="mt-3 mb-3">
    <ul class="nav justify-content-center nav-pills">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:profile' %}">Profile</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:user_register' %}">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:user_login' %}">Singup</a>
        </li>
        {% endif %}
    </ul>

</div>

post/templates/main/post_detail.html
{% extends 'main/base.html' %}

{% block title %}Post detail{% endblock %}

{% block content %}

{% if user == post.author %}
<div>
    <a href="{% url 'post_create' %}">Create</a>
    <a href="{% url 'post_update' post.slug %}">Update</a>
    <a href="{% url 'post_delete' post.slug %}">Delete</a>
</div>

{% endif %}
<div>
    <h4>{{ post.title }}</h4>
    <p>{{ post.body }}</p>

    <div>
        {% for comment in comments %}
            <div>
                <p>{{ comment }}</p>
            </div>
        {% endfor %}
    </div>

    <h3>Add comment:</h3>
    <form action="" method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            <p>{{ field }}</p>
            {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
    {% endfor %}
    <button type="submit">Add</button>
    </form>
</div>
{% endblock %}

users/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
{% include 'main/path/head.html' %}

{% block content %}
{% endblock %}

</body>
</html>

users/templates/main/profile.html
{% extends 'main/base.html' %}

{% block title %}Update{% endblock %}

{% block content %}
{{ profile }}

<div>
    <h4>Create post</h4>
    <p>
        <a href="{% url 'post_create' %}">Create</a>
    </p>

    <div class="list-group w-25 m-3">
        {% for post in user_posts  %}
            <a href="{% url 'post_detail' post.slug %}"
                class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-1 justify-content-between">
                <h5 class="mb-1">{{ post.title }}</h5>
                <small>{{ post.create_at|date:"D d M Y" }}</small>
            </div>
                <p class="mb-1">{{ post.discription|truncatewords:17 }}</p>
                <small>Donec id elit non mi porta.</small>
            </a>

        {% endfor %}
    </div>
</div>

{% endblock %}